-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 12:47:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblio` DEFAULT CHARACTER SET utf8 ;
USE `biblio` ;

-- -----------------------------------------------------
-- Table `biblio`.`oeuvres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`oeuvres` (
  `NO` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(150) NULL,
  `auteur` VARCHAR(100) NULL,
  `anee` INT NOT NULL,
  `genre` VARCHAR(30) NULL,
  PRIMARY KEY (`NO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblio`.`livres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`livres` (
  `NL` INT NOT NULL AUTO_INCREMENT,
  `editeur` VARCHAR(50) NULL,
  `oeuvres_NO` INT NOT NULL,
  PRIMARY KEY (`NL`, `oeuvres_NO`),
  INDEX `fk_livres_oeuvres1_idx` (`oeuvres_NO` ASC) VISIBLE,
  CONSTRAINT `fk_livres_oeuvres1`
    FOREIGN KEY (`oeuvres_NO`)
    REFERENCES `biblio`.`oeuvres` (`NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblio`.`adherents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`adherents` (
  `NA` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NULL,
  `prenom` VARCHAR(30) NULL,
  `adr` VARCHAR(100) NULL,
  `tel` CHAR(10) NULL,
  PRIMARY KEY (`NA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblio`.`emprunter`
-- -----------------------------------------------------
CREATE TABLE `biblio`.`emprunter` (
  `livres_NL` INT NOT NULL,
  `dateEmp` DATE NOT NULL,
  `dureeMax` INT NOT NULL,
  `dateRet` DATE NULL,
  `adherents_NA` INT NOT NULL,
  PRIMARY KEY (`dateEmp`, `livres_NL`, `adherents_NA`),
  INDEX `fk_emprunter_livres1_idx` (`livres_NL` ASC) VISIBLE,
  INDEX `fk_emprunter_adherents1_idx` (`adherents_NA` ASC) VISIBLE,
  CONSTRAINT `fk_emprunter_livres1`
    FOREIGN KEY (`livres_NL`)
    REFERENCES `biblio`.`livres` (`NL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprunter_adherents1`
    FOREIGN KEY (`adherents_NA`)
    REFERENCES `biblio`.`adherents` (`NA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
